# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amir Shadaab Mohammed
email: mohdamirshadaab@gmail.com
description: This is my blog where I'll write about anything from technology to philosophy.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "amirshdaab.github.io" # the base hostname & protocol for your site
twitter_username: amirshadaab
github_username:  amirshdaab

# Build settings
markdown: kramdown
 lsi: false
 safe: true
 source: amirshdaab.github.io
 incremental: false
 highlighter: rouge
 gist:
   noscript: false
 kramdown:
   math_engine: mathjax
